{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praesto.metricsServiceName" . }}
  namespace: {{ include "praesto.namespace" . }}
  labels:
    {{- include "praesto.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "praesto.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if and .Values.metrics.enabled .Values.webhooks.enabled }}
---
{{- end }}
{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praesto.webhookServiceName" . }}
  namespace: {{ include "praesto.namespace" . }}
  labels:
    {{- include "praesto.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.webhooks.service.port }}
    protocol: TCP
    targetPort: webhook-server
  selector:
    {{- include "praesto.selectorLabels" . | nindent 4 }}
{{- end }}
