apiVersion: praesto.praesto.io/v1alpha1
kind: ModelCacheNode
metadata:
  labels:
    app.kubernetes.io/name: praesto
    app.kubernetes.io/managed-by: kustomize
  name: modelcachenode-sample
spec:
  # TODO(user): Add fields here
