apiVersion: v2
name: praesto
description: Praesto Kubernetes operator for model cache lifecycle and Pod injection
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - kubernetes
  - operator
  - model-cache
  - ai
home: https://github.com/federicolepera/praesto
sources:
  - https://github.com/federicolepera/praesto
maintainers:
  - name: Federico Le Pera
