nameOverride: ""
fullnameOverride: ""

namespaceOverride: ""

image:
  repository: ghcr.io/federicolepera/praesto
  tag: "0.6.2"
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

leaderElection:
  enabled: true

metrics:
  enabled: true
  bindAddress: ":8443"
  service:
    port: 8443
  authProxy:
    enabled: true

webhooks:
  enabled: true
  certManager:
    enabled: true
    issuer:
      create: true
      name: ""
    certificate:
      create: true
      name: ""
      secretName: webhook-server-cert
  service:
    port: 443
    targetPort: 9443
  failurePolicy: Fail
  mutating:
    namespaceSelector:
      matchLabels:
        praesto.io/model-cache-injection: enabled

rbac:
  create: true
  aggregateRoles:
    create: true

downloader:
  image:
    repository: ghcr.io/federicolepera/praesto/downloader
    tag: "0.6.2"

localCache:
  basePath: /var/praesto

csi:
  enabled: true
  driverName: csi.praesto.io
  kubeletRootDir: /var/lib/kubelet
  image:
    repository: ghcr.io/federicolepera/praesto/csi-node-driver
    tag: "0.6.2"
    pullPolicy: IfNotPresent
  registrar:
    image:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.13.0
      pullPolicy: IfNotPresent
    resources: {}
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  updateStrategy:
    type: RollingUpdate
  resources: {}
  securityContext:
    privileged: true
    allowPrivilegeEscalation: true

nodeAgent:
  enabled: true
  image:
    repository: ghcr.io/federicolepera/praesto/node-agent
    tag: "0.6.2"
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsUser: 0
  updateStrategy:
    type: RollingUpdate
